connects to the latest 3 ip addresses
chrshdl/gt7-simdash pull request #12
Opened 2024-09-01 20:08 UTC by Omega1902

- latest 3 connected playstations are saved in config file
- most recent one always on top
- displays recent connected playstation ip addresses in wizard
- change config location

2024-09-01 20:29 UTC, chrshdl commented
Check the signature of `def parse_config(cls, path: Path) -> "Config"` in `configs.py` Shouldn't it return a Config object?

2024-09-01 21:06 UTC, chrshdl requested changes

2024-09-01 21:06 UTC, chrshdl commented on hmi/views/wizard.py
We would enhance the UX, if the recent ip addresses where accessible from the textfield or from a button right to the textfield. The user clicks on the textfield  or on an arrow pointing down [v], where a dropdown-like area opens and can choose the (recent) ip. What do you think?

2024-09-02 04:43 UTC, Omega1902 commented on hmi/widgets/textfield.py
> +            case x if len(x) >= 7:
That's a wildcard. In this case it has the same value as txt, the scope is just within this case-statement

2024-09-02 04:55 UTC, Omega1902 commented on configs.py
Type hints are about fuzzy on returning itself (class you are still defining). The good solution was introduced with python 3.11:
https://peps.python.org/pep-0673/

I'll check if the quotation marks are still necessary in python 3.10

2024-09-02 04:57 UTC, Omega1902 commented on hmi/views/wizard.py
I thought of using the right half for current connected IP addresses. That's why I left it empty for now

2024-09-02 20:10 UTC, Omega1902 commented on configs.py
It seems that they aren't for mypy and python 3.10. Since pyright (which I use locally) needs it, I'd like to keep the quotation marks for now

2024-09-02 20:11 UTC, Omega1902 commented on hmi/views/wizard.py
Moved Buttons to the right half. They also try to connect immediatly instead of needing the "OK" button pressed afterwards

2024-09-03 16:28 UTC, chrshdl commented
looks good, we can merge it :+1:

2024-09-03 16:42 UTC, merged